<link rel="stylesheet" href="{{ asset('platform/css/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ asset('platform/css/animate.min.css') }}">
<link rel="stylesheet" href="{{ asset('platform/css/magnific-popup.css') }}">
<link rel="stylesheet" href="{{ asset('platform/fontawesome/css/all.min.css') }}">
<link rel="stylesheet" href="{{ asset('platform/css/dripicons.css') }}">
<link rel="stylesheet" href="{{ asset('platform/css/slick.css') }}">
<link rel="stylesheet" href="{{ asset('platform/css/meanmenu.css') }}">
<link rel="stylesheet" href="{{ asset('platform/css/default.css') }}">
<link rel="stylesheet" href="{{ asset('platform/css/style.css') }}">
<link rel="stylesheet" href="{{ asset('platform/css/responsive.css') }}">
